name: 'Hello World'
description: 'Greet someone'
inputs:
  deployment-type:
    required: true
    default: 'site'
  operation:
    required: true
    default: 'get'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Do the Auth
      id: auth
      run: echo "Auth to GCP"
      shell: bash

    - name: get site
      id: get
      run: |
        if [ ${{ imputs.operation }} == 'get' ]; then
          echo "Getting ${{ inputs.deployment-type }} id"
        else
          echo "Skipping performing get"
      shell: bash

    - name: release the site
      id: release
      run: |
        if [ ${{ imputs.operation }} == 'release' ]; then
          echo "Releasing ${{ inputs.deployment-type }} id"
        else
          echo "Skipping performing release"
      shell: bash

    - name: seed with firestoredb
      id: seed
      run: |
        if [ ${{ imputs.operation }} == 'seed' ]; then
          echo "Seeding ${{ inputs.deployment-type }}"
        else
          echo "Skipping performing seed"
      shell: bash