name: hello
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      who-to-greet:
        required: true
        type: string
        default: 'World'
jobs:
  hello_world_job:
    name: A job to say hello
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: farhan-TheITguy/hello-action
        ref: main
        path: hello-action
    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
    - name: Run some commands
      run: |
        pwd
        whoami
        ls -al
      shell: bash
