name: Release Prefix
on:
  workflow_dispatch:
    inputs:
      deployment-type:
        type: string
        description: site or supersite
        default: site
      environment-prefix:
        type: string
        description: prefix to release
        default: ab12c
  workflow_call:
    inputs:
      deployment-type:
        type: string
        description: site or supersite
        default: site
      environment-prefix:
        type: string
        description: prefix to release
        default: ab12c
jobs:
  release-prefix:
    name: Release Prefix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: farhan-TheITguy/hello-action
          ref: main
          path: hello-action
        #   token: ${{ secrets.GHA_PAT }}

      - name: Release the Site or Supersite prefix
        id: release-prefix
        shell: bash
        run: |
          python release.py --deployment-type ${{ inputs.deployment-type }} --prefix ${{ inputs.environment-prefix }} 
        working-directory: ./hello-action/scripts