name: test
on:
  workflow_dispatch:
  workflow_call:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - name: test step
        id: test
        shell: bash
        run: |
          echo "This is from test workflow!!"
          pwd
          whoami
          ls -alrth
          echo "---> One dir back"
          ls -alrth ../
          echo "---> Two dir back"
          ls -alrth ../../
          echo "---> Three dir back"
          ls -alrth ../../../
        
