name: test
on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: test step
        id: test
        shell: bash
        run: |
          echo "This is from test workflow!!"
          pwd
          whoami
          ls -lrth
        
